### ISSUE TITLE
R is broken

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene-tests#80]
R doesn't run as is (due to `trusted_files.libstdc++` -- plus signs are not allowed in manifests). Even after fixing this issue manually, R segfaults on one of the examples.

Need to update its Makefile and manifest and fix all found bugs.

**Comment by mkow** [comment]
Could you migrate this issue to the main repository?

**Comment by dimakuv** [comment]
Done, see https://github.com/oscarlab/graphene/issues/1390.

Closing this.
